pipeline:
  name: hello-lambda-api
  identifier: Build_harness_prototype_1755833382578
  projectIdentifier: harnessprototype
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  name: Node Test
                  identifier: node_test
                  type: Run
                  spec:
                    shell: Sh
                    image: node:20
                    command: |
                      node -v
                      npm --version
                      apt-get update && apt-get install -y zip
                      npm ci --prefix app
                      npm test --prefix app
                      (cd app && zip -r ../build.zip . -x "test/*")
                      ls -lh build.zip
              - step:
                  name: Upload to S3
                  identifier: upload_s3
                  type: Run
                  spec:
                    shell: Sh
                    image: amazon/aws-cli:2.15.46
                    connectorRef: credentialsaws
                    envVariables:
                      AWS_DEFAULT_REGION: us-east-1
                      ARTIFACT_BUCKET: hello-lambda-api-artifacts-cecconi
                      ARTIFACT_KEY: hello-lambda-api/builds/build.zip
                    command: |
                      set -e
                      aws s3 ls "s3://${ARTIFACT_BUCKET}" >/dev/null
                      aws s3 cp build.zip "s3://${ARTIFACT_BUCKET}/${ARTIFACT_KEY}" --only-show-errors
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: stack-creation
        identifier: stackcreation
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: helloapi
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
        tags: {}
        strategy:
          parallelism: 1
        when:
          pipelineStatus: Success
  properties:
    ci:
      codebase:
        connectorRef: SecretGitHub
        repoName: harness-prototype
        build: <+input>
